version: 2

sources:
    - name: staging
      database: de4jsjsel5i78g
      schema: api_schema
      tables:
        - name: swapi_data
        # - name: swapi_data
         # freshness:
           # error_after: {count: 6, period: hour}
