name: ci_swapi_api_dbt_run
on:
#  pull_request:
#    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HEROKU_DEMO_PG_PORT: ${{ secrets.HEROKU_DEMO_PG_PORT }}
      HEROKU_DEMO_PG_HOST: ${{ secrets.HEROKU_DEMO_PG_HOST }}
      HEROKU_DEMO_PG_USER: ${{ secrets.HEROKU_DEMO_PG_USER }}
      HEROKU_DEMO_PG_PASS: ${{ secrets.HEROKU_DEMO_PG_PASS }}
      HEROKU_DEMO_PG_DB: ${{ secrets.HEROKU_DEMO_PG_DB }}
      HEROKU_DEMO_PG_SCHEMA: ${{ secrets.HEROKU_DEMO_PG_SCHEMA }}
      HEROKU_DEMO_PG_TABLE: ${{ secrets.HEROKU_DEMO_PG_TABLE }}
      
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: install dbt and python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install psycopg2
          pip install sqlalchemy
          pip install starwar-dob
          pip install dbt-postgres
          
      - name: run python script
        run: python pipeline.py
        
      - name: run dbt
        run: |
          cd swapi_dbt
          dbt build --profiles-dir .
